baseURL = "/"
publishDir = "docs"
languageCode = "en-us"
title = "Kubeplatform"
theme = "kube"
description = "Create production ready Development Platform for Kubernetes"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "kubeplatform" # add your company name
  github = "kube-platform" # add your github profile name
  email = "myemail@myaddress.xxx"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
